In [1]:
%pip install nptyping beartype

   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.1 MB 207.2 kB/s eta 0:00:03
   ------------------ --------------------- 0.5/1.1 MB 207.2 kB/s eta 0:00:03
   ------------------ --------------------- 0.5/1.1 MB 207.2 kB/s eta 0:00:03
   ------------------ --------------------- 0.5/1.1 MB 207.2 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.1 MB 256.1 kB/s eta 0:00:02
   --------------------------- ------------ 0.8/1.1 MB 256

https://github.com/ramonhagenaars/nptyping/blob/master/USERDOCS.md#Quickstart

# scalar value

In [4]:
import numpy as np
# from nptyping import NDArray # es ka andar 2 chiza pass hoti hai 1) shap 2) data_type

a : np.ndarray = np.array(1000) # object to store data
display(a) # print data
display(a.shape) # print the shape of object
display(a.dtype) # print the data type
display(a.ndim) # print the dimension
display(a.size) # print the size
display(a.itemsize) # print the item size
display(type(a)) # print the type

array(1000)

()

dtype('int32')

0

1

4

numpy.ndarray

# vactor type

In [7]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # vector object to store data
display(f"object {a}") # print data
display(f"object shape  {a.shape}") # print the shape of object
display(f" object data type{a.dtype}") # print the data type
display( f"object dimension {a.ndim}") # print the dimension 
display(f"object size {a.size}") # print the size
display(f"object item size {a.itemsize}") # print the item size
display(f"object type {type(a)}") # print the type
# help(a.itemsize)

'object [1 2 3 4]'

'object shape  (4,)'

' object data typeint32'

'object dimension 1'

'object size 4'

'object item size 4'

"object type <class 'numpy.ndarray'>"

## Matrix

In [ ]:
import numpy as np

a : np.ndarray = np.array([[1,2,3,4] , [6,7,8,9] , [10,11,12,13]]) # vector object to store data
display(f"object {a}") # print data
display(f"object shape  {a.shape}") # print the shape of object
display(f" object data type{a.dtype}") # print the data type
display( f"object dimension {a.ndim}") # print the dimension 
display(f"object size {a.size}") # print the size
display(f"object item size {a.itemsize}") # print the item size
display(f"object type {type(a)}") # print the type

'object [[ 1  2  3  4]\n [ 6  7  8  9]\n [10 11 12 13]]'

'object shape  (3, 4)'

' object data typeint32'

'object dimension 2'

'object size 12'

'object item size 4'

"object type <class 'numpy.ndarray'>"

# numpy with NDArray typing support 

In [18]:
from nptyping import NDArray, Shape, UInt16
import numpy as np
from typing import  Any

a : NDArray[Shape["10"] , Any] = np.arange(10) # vector object to store Any type data
a : NDArray[Shape["10"] , UInt16] = np.arange(10)
print(a)

data: NDArray[Shape["10, 3"], UInt16] = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18], [19,20,21], [22,23,24], [25,26,27], [28,29,30]])
print(data)
print(data.ndim)
data + 5 # add 5 to all elements of array
print(data)

[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [ ]:
from nptyping import NDArray, Shape, UInt16
import numpy as np
from typing import  Any


a : NDArray[Shape["99"] , Any] = np.arange(100) # vector object to store Any type data

# yha  time itna nhi laga ga
a + 5

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [ ]:
%%time

b : list[int] = range(100)

# esma ya time zada lag sakta hai
[ b + 5 for b in b]

CPU times: total: 0 ns
Wall time: 997 μs


[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104]

# numpy advanced operation vs list operation 

In [40]:
data = list(range(100))

print(data[20:30])
data[20:30] = 100 #  normal python list
print(data[20:30])


[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


TypeError: must assign iterable to extended slice

In [ ]:

ndata : NDArray[Shape["99"] , UInt16] = np.arange(100)
print(ndata[20:30] )
ndata[20:30] = 100 # allow update in list using numpy
print(ndata)



[20 21 22 23 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 100 100 100 100 100 100 100 100 100 100  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99]


# Numpy 1d functions

In [ ]:
statr_bank : NDArray[Shape["10"] , UInt16] = np.array([1,7,8,9,10]) 

ubl_bank : NDArray[Shape["100"] , UInt16] = np.random.randint(1 ,100 , 20 ) # generate random number

print(statr_bank)
print(ubl_bank)

[ 1  7  8  9 10]
[98 91 82 29 86 12 80 58 86 50 24 45 40 92 62 60 85 95 93  3]


# boolean indexing

In [ ]:
statr_bank : NDArray[Shape["10"] , UInt16] = np.array([1,7,8,10]) 

# [1,      7,    8,    10]
#[True, False, False, True]
# Variable[1,      7,    8,    10]

arr = np.array([5, 10, 15, 20, 25])
mask = np.array([True, False, True, False, True])  
print(arr[mask]) # [5, 15, 25] print only true value


# Jab tumhare paas large dataset ho aur sirf specific values chahiye, tab Boolean indexing kaam aati hai.


# Suppose ek list of students' marks hai
marks = np.array([50, 80, 90, 40, 70])

# Sirf passing marks chahiye (60 se zyada wale)
passing = marks >= 60  # Condition check

print(marks[passing])  


[ 5 15 25]
[80 90 70]


In [ ]:
statr_bank : NDArray[Shape["10"] , UInt16] = np.array([1,7,8,10]) 
statr_bank % 2  == 0 # even number

array([False, False,  True,  True])

In [ ]:
statr_bank : NDArray[Shape["10"] , UInt16] = np.array([1,7,8,10]) 
statr_bank[statr_bank % 2  == 0] # print only even number

array([ 8, 10])

#  numpy.in1d()

* numpy.in1d() dono arrays ka comparison karta hai aur check karta hai ke pehle array ke elements dusre array me hain ya nahi.

* Iska output Boolean array hota hai jo batata hai ke kaunse elements present hain aur kaunse nahi.



In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])  # Array1
b = np.array([3, 4, 7, 8])     # Array2

result = np.in1d(a, b) # check if elements of Array1 are present in Array2
print(result)  # Output: [False, False,  True,  True, False]


[False False  True  True False]


In [ ]:
result = np.in1d(a, b) # check if elements of Array1 are present in Array2
print(a[result]) # a[] karna sa true value print karega

[3 4]


In [ ]:
# Agar tumhe sirf common elements chahiye, to in1d() ko indexing ke saath use kar sakte hai.
common_elements = a[np.in1d(a, b)]
print(common_elements)


[3 4]


In [54]:

np.intersect1d(a,b) # es ka ya faida hai ka ya hama direct value ko return kara ga true false ma answer nhi kara ga 
                    # kam ya in1d ka hi karaga

                    

array([3, 4])

# numpy.where()
* numpy.where() ek conditional function hai jo kisi condition ke basis pe array ke elements ko filter ya replace karta hai.
* Agar condition True hoti hai, to us index ka value return ya replace karta hai.


numpy.where(condition, x, y)

condition → Jo check karni hai (True ya False).

x → Jo value return hogi agar condition True ho.

y → Jo value return hogi agar condition False ho.

Agar sirf condition dete ho, to True wale indexes return hotay hain.

In [58]:
#  Indexes Find Karna

import numpy as np

a = np.array([10, 20, 30, 40, 50])

indexes = np.where(a > 25)
print(indexes)

(array([2, 3, 4], dtype=int64),)


In [59]:
# Values Replace Karna

b = np.array([10, 25, 30, 15, 50])

new_array = np.where(b > 20, 1, 0)  # Agar value > 20 hai to 1, warna 0
print(new_array)

[0 1 1 0 1]


In [60]:
# Multiple Conditions

c = np.array([5, 15, 25, 35, 45])

result = np.where((c > 10) & (c < 40), "Inside", "Outside")
print(result)

['Outside' 'Inside' 'Inside' 'Inside' 'Outside']


In [61]:
#  2D Array Ke Saath Use

d = np.array([[1, 2, 3], [4, 5, 6]])

result = np.where(d % 2 == 0, "Even", "Odd")
print(result)

[['Odd' 'Even' 'Odd']
 ['Even' 'Odd' 'Even']]


# create a Numpy arrays

In [75]:
# a : NDArray[Shape["Any, Any"] , Any] = np.array([[1,2,3,4], [6,7,8,9]])  # 2D array  jitna chahay row colums da sakta hai q ka hamna yha type ma Any set kiya hai es ka matlab ha jitni row or colums add karna chaho kr lo 2d array ma dimention 2 honi chahiye lazmi

a : NDArray[Shape["Size, Size"] , Any] = np.array([[1,2,3,4], [6,7,8,9]])  # 2D array  jitna chahay row colums da sakta hai q ka hamna yha type ma Size set kiya hai es ka matlab ha jitni row or colums add karna chaho kr lo 2d array ma dimention 2 honi chahiye lazmi

print(a)

b: NDArray[Shape["*, *"] , Any] = np.array([[1,2,3,4], [6,7,8,9]]) 
print(b)

[[1 2 3 4]
 [6 7 8 9]]
[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
np.who() # to print all variable

Name                 Shape            Bytes            Type

_                    5                20               int32
__                   5                20               int32
a                    2 x 4            32               int32
arr                  5                20               int32
_22                  10               40               int32
_24                  99               396              int32
_29                  100              400              int32
b                    2 x 4            32               int32
ndata                100              400              int32
statr_bank           4                16               int32
ubl_bank             20               80               int32
mask                 5                5                bool
_47                  4                4                bool
marks                5                20               int32
passing              5                5                bool
_50                  2     

# Create Any dimension array

In [ ]:
# shortcut to create 2D array
a : NDArray[Shape["Size, Size"] , Any] = np.arange(3*3).reshape(3,3) # arange(3 row  3 coloumn) reshape(3,3) jo arrange ma likhi hai unha yha coma seprated likh da ga

b : NDArray[Shape["Size, Size"] , Any] = np.arange(3*4).reshape(3,4)
print(a) # print 3 row 3 coloumn  [[0 1 2] [3 4 5] [6 7 8]]
print(b) # print 3 row 4 coloumn  [[0 1 2 3] [4 5 6 7] [8 9 10 11]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# np.arange() + reshape() ka Use
* np.arange(n)

arange() ek sequence of numbers generate karta hai 0 se lekar (n-1) tak.
Yahaan n ko manually calculate kar rahe hain.
* .reshape(x, y, z)

Iska matlab hai ke hum is array ko ek 3D shape dena chahte hain.
(x, y, z) ka matlab hai:
x = Number of matrices (depth)
y = Number of rows in each matrix
z = Number of columns in each matrix

In [ ]:
# shortcut to create 3D array                             2d,3rows,3coloumn  
c : NDArray[Shape["Size, Size , Size"] , Any] = np.arange(2*3*3).reshape(2,3,3)
                                                       #  3d,3rows,4coloumn 
d : NDArray[Shape["Size, Size , Size"] , Any] = np.arange(3*3*4).reshape(3,3,4)
print(c)
print("=========================")
print(d) 


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


jitni dimension hogi utni hi ham slicing ma index pass kar sakta hai

np.arange(5*3*4)

Yeh ek sequence 0 se 59 tak generate karega.

Total 5*3*4 = 60 elements honge.

.reshape(5,3,4)

Isko 5 matrices (depth), har ek me 3 rows aur 4 columns me convert karega.


In [94]:
g : NDArray[Shape["Size, Size , Size"] , Any] = np.arange(5*3*4).reshape(5,3,4)
print(g[ :: , :: , ::]) # jitni dimension hogi utni hi ham slicing ma index pass kar sakta hai
# print("=====================================")
print(g[ ::2 , :: , ::]) 
print("=====================================")
print(g[ 1:3: , :: , ::]) # jitni dimension hogi utni hi ham slicing ma index pass kar sakta 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [95]:
g : NDArray[Shape["Size, Size , Size"] , Any] = np.arange(5*3*4).reshape(5,3,4)
g[g%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [96]:
np.asarray([1,2,3,4,5,6,7,8,9,10]) # convert list , tuple , anything to numpyarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
np.zeros(10) # create 1D array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.zeros((2,2)) # create 2D array of 2 zeros

array([[0., 0.],
       [0., 0.]])

In [101]:
np.ones(10) # create 1D array of 10 ones
print(np.ones(10))
print("=====================")
np.ones((2,2)) # create 2D array of 2 ones
print(np.ones((2,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [ ]:
a : NDArray[Shape["Size, Size"] , Any] = np.array([[1,2,3,4], [6,7,8,9]]) 
np.ones_like(a) # create 2D array of 2 ones  copy of a and  fill with ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [106]:
a : NDArray[Shape["Size, Size"] , Any] = np.array([[1,2,3,4],[1,2,3,4], [6,7,8,9]]) 
print(a[ [0,-1] , ::]) 

[[1 2 3 4]
 [6 7 8 9]]


In [115]:
ndata : NDArray[Shape["20"] , Any] = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(ndata.min()) # min value
print(ndata.max()) # max value
print(ndata.sum()) # sum of all value
print(ndata.mean()) # mean of all value
print(ndata.argmax()) # index of max value
print(ndata.argmin()) # index of min value
print(ndata.std()) # standard deviation
print(ndata.var()) # variance
print(ndata.shape) # shape of array
print(ndata.cumsum()) # cumulative sum
print(ndata.cumprod()) # cumulative product


1
20
210
10.5
19
0
5.766281297335398
33.25
(20,)
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736]
